language: go

go:
- "1.11.x"

env:
- GO111MODULE=on CGO_ENABLED=0

install:
- go mod download

jobs:
  include:
  - stage: test
    script: go test ./...
  - stage: build
    script: go build cmd/vaultify/vaultify.go
